services:
  postgres:
    image: docker.io/postgres:17
    restart: unless-stopped
    hostname: postgres
    volumes:
      - db_main:/var/lib/postgresql/data
      - ./pg_hba.conf:/etc/postgresql/pg_hba.conf
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test
    command: |
      postgres
      -c shared_preload_libraries=pg_stat_statements
      -c wal_level=replica
      -c hot_standby=on
      -c shared_buffers=512MB
      -c maintenance_work_mem=128MB
      -c effective_io_concurrency=2
      -c min_wal_size=1GB
      -c max_wal_size=3GB
      -c hba_file=/etc/postgresql/pg_hba.conf
    healthcheck:
      test: pg_isready --dbname=test
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s

  slave:
    hostname: slave
    image: docker.io/postgres:17
    restart: unless-stopped
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
      - db_slave:/var/lib/postgresql/data
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test
    healthcheck:
      test: pg_isready -h postgres --dbname=test -U postgres
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
volumes:
  db_main:
  db_slave:
